// <auto-generated />
using System;
using System.Collections.Generic;
using CarTrack_API.DataAccess.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarTrack_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250612204554_mig34")]
    partial class mig34
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppointmentDeal", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("DealId")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentId", "DealId");

                    b.HasIndex("DealId");

                    b.ToTable("AppointmentDeal");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<int>("MaintenanceRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("MechanicId")
                        .HasColumnType("integer");

                    b.Property<int>("RepairShopId")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceRecordId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("RepairShopId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Body", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DoorNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Body");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.ClientProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("ClientProfile");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("RepairShopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepairShopId");

                    b.ToTable("Deal");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.MaintenanceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceType");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.MaintenanceUnverifiedRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("AttachmentUrls")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<List<string>>("CustomMaintenanceNames")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DoneDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DoneMileage")
                        .HasColumnType("double precision");

                    b.Property<string>("EntryType")
                        .HasColumnType("text");

                    b.Property<List<int>>("RelatedConfigIds")
                        .HasColumnType("jsonb");

                    b.Property<string>("ServiceProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceUnverifiedRecord");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.MaintenanceVerifiedRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DoneDate")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("MaintenanceNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("RepairShopId")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepairShopId");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceRecord");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.ManagerProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("ManagerProfile");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.MechanicProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RepairShopId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("RepairShopId");

                    b.ToTable("MechanicProfile");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.MileageReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("OdometerValue")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("MileageReading");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RemiderId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RemiderId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Producer");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Reminder", b =>
                {
                    b.Property<int>("VehicleMaintenanceConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("DueDate")
                        .HasColumnType("integer");

                    b.Property<double>("DueMileage")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastDateCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LastMileageCkeck")
                        .HasColumnType("double precision");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("VehicleMaintenanceConfigId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Reminder");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.RepairShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("RepairShop");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.VehicleEngine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cylinders")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriveType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Horsepower")
                        .HasColumnType("integer");

                    b.Property<double>("Size")
                        .HasColumnType("double precision");

                    b.Property<int>("TorqueFtLbs")
                        .HasColumnType("integer");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VehicleEngine");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.VehicleInfo", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.Property<double>("AverageTravelDistance")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Mileage")
                        .HasColumnType("double precision");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicleId");

                    b.ToTable("VehicleInfo");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.VehicleMaintenanceConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DateIntervalConfig")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<int>("MaintenanceTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("MileageIntervalConfig")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceTypeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleMaintenanceConfig");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BodyId")
                        .HasColumnType("integer");

                    b.Property<long>("Consumption")
                        .HasColumnType("bigint");

                    b.Property<long>("FuelTankCapacity")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProducerId")
                        .HasColumnType("integer");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleEngineId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BodyId");

                    b.HasIndex("ProducerId");

                    b.HasIndex("VehicleEngineId");

                    b.ToTable("VehicleModel");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.VehiclePaper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaperType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ValabilityDays")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehiclePaper");
                });

            modelBuilder.Entity("AppointmentDeal", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTrack_API.EntityLayer.Models.Deal", null)
                        .WithMany()
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Appointment", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.MaintenanceVerifiedRecord", "MaintenanceVerifiedRecord")
                        .WithMany("Appointments")
                        .HasForeignKey("MaintenanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTrack_API.EntityLayer.Models.MechanicProfile", "Mechanic")
                        .WithMany("Appointments")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTrack_API.EntityLayer.Models.RepairShop", "RepairShop")
                        .WithMany("Appointments")
                        .HasForeignKey("RepairShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTrack_API.EntityLayer.Models.Vehicle", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaintenanceVerifiedRecord");

                    b.Navigation("Mechanic");

                    b.Navigation("RepairShop");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.ClientProfile", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.User", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("CarTrack_API.EntityLayer.Models.ClientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Deal", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.RepairShop", "RepairShop")
                        .WithMany("Deals")
                        .HasForeignKey("RepairShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairShop");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.MaintenanceUnverifiedRecord", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.Vehicle", "Vehicle")
                        .WithMany("MaintenanceUnverifiedRecord")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.MaintenanceVerifiedRecord", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.RepairShop", null)
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("RepairShopId");

                    b.HasOne("CarTrack_API.EntityLayer.Models.Vehicle", "Vehicle")
                        .WithMany("MaintenanceVerifiedRecord")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.ManagerProfile", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.User", "User")
                        .WithOne("ManagerProfile")
                        .HasForeignKey("CarTrack_API.EntityLayer.Models.ManagerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.MechanicProfile", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.RepairShop", "RepairShop")
                        .WithMany("Mechanics")
                        .HasForeignKey("RepairShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTrack_API.EntityLayer.Models.User", "User")
                        .WithOne("MechanicProfile")
                        .HasForeignKey("CarTrack_API.EntityLayer.Models.MechanicProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairShop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.MileageReading", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.Vehicle", "Vehicle")
                        .WithMany("MileageReadings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Notification", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.Reminder", "Reminder")
                        .WithMany("Notifications")
                        .HasForeignKey("RemiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTrack_API.EntityLayer.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTrack_API.EntityLayer.Models.Vehicle", "Vehicle")
                        .WithMany("Notifications")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.RefreshToken", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("CarTrack_API.EntityLayer.Models.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Reminder", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.Status", "Status")
                        .WithMany("Reminders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTrack_API.EntityLayer.Models.Vehicle", null)
                        .WithMany("Reminders")
                        .HasForeignKey("VehicleId");

                    b.HasOne("CarTrack_API.EntityLayer.Models.VehicleMaintenanceConfig", "VehicleMaintenanceConfig")
                        .WithOne("Reminder")
                        .HasForeignKey("CarTrack_API.EntityLayer.Models.Reminder", "VehicleMaintenanceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("VehicleMaintenanceConfig");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.RepairShop", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.ManagerProfile", "Manager")
                        .WithMany("RepairShops")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.User", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Vehicle", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.ClientProfile", "Client")
                        .WithMany("Vehicles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTrack_API.EntityLayer.Models.VehicleModel", "VehicleModel")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.VehicleInfo", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.Vehicle", "Vehicle")
                        .WithOne("VehicleInfo")
                        .HasForeignKey("CarTrack_API.EntityLayer.Models.VehicleInfo", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.VehicleMaintenanceConfig", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.MaintenanceType", "MaintenanceType")
                        .WithMany("VehicleMaintenanceConfigs")
                        .HasForeignKey("MaintenanceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTrack_API.EntityLayer.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleMaintenanceConfigs")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaintenanceType");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.VehicleModel", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.Body", "Body")
                        .WithMany("VehicleModels")
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTrack_API.EntityLayer.Models.Producer", "Producer")
                        .WithMany("VehicleModels")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTrack_API.EntityLayer.Models.VehicleEngine", "VehicleEngine")
                        .WithMany("VehicleModels")
                        .HasForeignKey("VehicleEngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Body");

                    b.Navigation("Producer");

                    b.Navigation("VehicleEngine");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.VehiclePaper", b =>
                {
                    b.HasOne("CarTrack_API.EntityLayer.Models.Vehicle", "Vehicle")
                        .WithMany("VehiclePapers")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Body", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.ClientProfile", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.MaintenanceType", b =>
                {
                    b.Navigation("VehicleMaintenanceConfigs");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.MaintenanceVerifiedRecord", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.ManagerProfile", b =>
                {
                    b.Navigation("RepairShops");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.MechanicProfile", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Producer", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Reminder", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.RepairShop", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Deals");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("Mechanics");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Status", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.User", b =>
                {
                    b.Navigation("ClientProfile")
                        .IsRequired();

                    b.Navigation("ManagerProfile")
                        .IsRequired();

                    b.Navigation("MechanicProfile")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("RefreshToken")
                        .IsRequired();
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.Vehicle", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MaintenanceUnverifiedRecord");

                    b.Navigation("MaintenanceVerifiedRecord");

                    b.Navigation("MileageReadings");

                    b.Navigation("Notifications");

                    b.Navigation("Reminders");

                    b.Navigation("VehicleInfo")
                        .IsRequired();

                    b.Navigation("VehicleMaintenanceConfigs");

                    b.Navigation("VehiclePapers");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.VehicleEngine", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.VehicleMaintenanceConfig", b =>
                {
                    b.Navigation("Reminder")
                        .IsRequired();
                });

            modelBuilder.Entity("CarTrack_API.EntityLayer.Models.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
